<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWVxzHDd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWVxzHDd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWVxzHDd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWVxzHDd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWVxzHDd\App_KernelDevDebugContainer([
    'container.build_hash' => 'WVxzHDd',
    'container.build_id' => '6ac46379',
    'container.build_time' => 1696842182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWVxzHDd');
